error: change how missing items are rendered
Also changed how executor and parser errors are combined to handle
"expected XXX, missing YYY" scenario a bit better